apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: weather-notify
  namespace: default
rules:
- apiGroups:
      - ""
      - batch
  resources:
      - persistentvolumes
      - persistentvolumeclaims
      - cronjobs
  verbs: ["get", "list", "create"]